// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_4LdbRbuK3-u6C2W0gIHKnMS2lH3MDo',
    appId: '1:653074860985:web:67bb49b6170161273cc468',
    messagingSenderId: '653074860985',
    projectId: 'meu-app-pokedex-br',
    authDomain: 'meu-app-pokedex-br.firebaseapp.com',
    storageBucket: 'meu-app-pokedex-br.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrULWyadi00bNcS2yzBwh_-P4rkhGnYS4',
    appId: '1:653074860985:android:c0b69ca5eb74f8093cc468',
    messagingSenderId: '653074860985',
    projectId: 'meu-app-pokedex-br',
    storageBucket: 'meu-app-pokedex-br.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuNSGzy33QVoPX0k2Baec06W6ocQzfTg8',
    appId: '1:653074860985:ios:0027dff1bbff70d23cc468',
    messagingSenderId: '653074860985',
    projectId: 'meu-app-pokedex-br',
    storageBucket: 'meu-app-pokedex-br.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );
}
